use crate::{
    components::image::Image,
    utils::{EnumCast, hooks::use_setter},
};
use tutorlolv2_gen::{ChampionId, ItemId, RuneId};
use yew::prelude::*;

#[derive(Properties, PartialEq)]
struct CodeDocsProps<T: PartialEq> {
    pub title: &'static str,
    pub value: T,
    pub callback: Callback<T>,
}

#[component]
fn Disclaimer() -> Html {
    html! {
        <>
            <h1 class={classes!("text-4xl", "font-bold")}>{"Source code"}</h1>
            <p>
                {"This section provides the source code that was being used "}
                {"internally by the online calculator service during the time "}
                {"of deployment of this Windows application/website. Because of "}
                {"that, the following code can be outdated, and if you want to "}
                {"verify what is currently being used, you have to check the "}
                {"GitHub repository at folder/crate "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://raw.githubusercontent.com/LuizGomes56/tutorlolv2/refs/heads/master/tutorlolv2_gen/src/data.rs"}
                >
                    {"tutorlolv2_gen/src/data.rs"}
                </a>
                {". Note that this file is automatically generated and I will "}
                {"deny manual changes to it. If something needs to be changed, then "}
                {"the whole update process have to occur normally, and any exception "}
                {"should be added to the build script, not to the generated file"}
            </p>
            <h1 class={classes!("text-4xl", "font-bold")}>{"How is all this information gathered?"}</h1>
            <p>
                {"This app uses "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://github.com/meraki-analytics/lolstaticdata"}
                >
                    {"meraki-analytics/lolstaticdata"}
                </a>
                {" to generate the formulas used to calculate the damages of items, "}
                {"and champion abilities, and they depend on the game's wiki. If any of "}
                {"them becomes outdated, so will this app. After downloading and caching "}
                {"their JSON files, custom files for each item and champion will run to "}
                {"generate an intermediary JSON file with damage formulas for each instance. "}
                {"All the logic related to it is located in crate "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://github.com/LuizGomes56/tutorlolv2/tree/master/tutorlolv2_dev"}
                >
                    {"tutorlolv2_dev"}
                </a>
            </p>
        </>
    }
}

#[derive(Clone, Copy, Default, PartialEq)]
enum View {
    #[default]
    Champion,
    Item,
    Rune,
}

#[component]
pub fn Docs() -> Html {
    let view = use_state(View::default);
    let champion_id = use_state(ChampionId::random);
    let item_id = use_state(ItemId::random);
    let rune_id = use_state(RuneId::random);

    let champion_callback = use_setter(&champion_id);
    let item_callback = use_setter(&item_id);
    let rune_callback = use_setter(&rune_id);

    html! {
        <main class={classes!(
            "flex-grow", "flex", "w-full", "overflow-auto",
            "pt-4", "pb-8", "px-6", "flex-col", "gap-4"
        )}>
            <Disclaimer />

        </main>
    }
}
