use crate::{
    components::image::Image,
    utils::{EnumCast, hooks::use_setter},
};
use tutorlolv2_gen::{ChampionId, ItemId, RuneId};
use yew::prelude::*;

#[derive(Properties, PartialEq)]
struct CodeDocsProps<T: PartialEq> {
    pub title: &'static str,
    pub value: T,
    pub callback: Callback<T>,
}

#[component]
fn CodeDocs<T: EnumCast>(props: &CodeDocsProps<T>) -> Html {
    let CodeDocsProps {
        title,
        value,
        callback,
    } = props;

    let is_open = use_state(|| false);
    let is_open_setter = use_setter(&is_open);
    let is_open_callback = {
        let is_open_setter = is_open_setter.clone();
        move |boolean| is_open_setter.emit(boolean)
    };

    let selector = use_memo(callback.clone(), |callback| {
        T::ARRAY
            .into_iter()
            .map(|element| {
                let onclick = {
                    let callback = callback.clone();
                    let is_open_callback = is_open_callback.clone();
                    move |_| {
                        is_open_callback(false);
                        callback.emit(*element)
                    }
                };
                html! {
                    <div {onclick} class={classes!(
                        "px-1.5", "py-1", "hover:bg-std-800", "text-lg",
                        "flex", "items-center", "gap-3", "font-medium",
                        "first:pt-1.5", "last:pb-1.5"
                    )}>
                        <Image src={element.image_type()} class={classes!("w-8")} />
                        <span class={classes!("whitespace-nowrap")}>{element.name()}</span>
                    </div>
                }
            })
            .collect::<Html>()
    });

    html! {
        <div class={classes!("flex", "flex-col", "gap-4")}>
            <h1 class={classes!("text-4xl", "font-bold")}>{*title}</h1>
            <button
                class={classes!(
                    "relative", "w-fit", "py-2", "rounded-xl",
                    "hover:bg-std-950", "transition-colors"
                )}
                onclick={{
                    let is_open = is_open.clone();
                    move |_| is_open_callback(!*is_open)
                }}
            >
                <div class={classes!("flex", "items-center", "gap-4")}>
                    <Image src={value.image_type()} class={classes!("ml-2", "w-12")} />
                    <h2 class={classes!("text-3xl", "font-bold", "pr-4")}>{value.name()}</h2>
                </div>
                <div class={classes!(
                    "absolute", "max-h-64", "bg-std-800", "overflow-auto",
                    "flex", "flex-col", "mt-4"
                )}>
                    {is_open.then_some((*selector).clone())}
                </div>
            </button>
            <code>{value.html()}</code>
        </div>
    }
}

#[component]
fn Disclaimer() -> Html {
    html! {
        <>
            <h1 class={classes!("text-4xl", "font-bold")}>{"Source code"}</h1>
            <p>
                {"This section provides the source code that was being used "}
                {"internally by the online calculator service during the time "}
                {"of deployment of this Windows application/website. Because of "}
                {"that, the following code can be outdated, and if you want to "}
                {"verify what is currently being used, you have to check the "}
                {"GitHub repository at folder/crate "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://raw.githubusercontent.com/LuizGomes56/tutorlolv2/refs/heads/master/tutorlolv2_gen/src/data.rs"}
                >
                    {"tutorlolv2_gen/src/data.rs"}
                </a>
                {". Note that this file is automatically generated and I will "}
                {"deny manual changes to it. If something needs to be changed, then "}
                {"the whole update process have to occur normally, and any exception "}
                {"should be added to the build script, not to the generated file"}
            </p>
            <h1 class={classes!("text-4xl", "font-bold")}>{"How is all this information gathered?"}</h1>
            <p>
                {"This app uses "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://github.com/meraki-analytics/lolstaticdata"}
                >
                    {"meraki-analytics/lolstaticdata"}
                </a>
                {" to generate the formulas used to calculate the damages of items, "}
                {"and champion abilities, and they depend on the game's wiki. If any of "}
                {"them becomes outdated, so will this app. After downloading and caching "}
                {"their JSON files, custom files for each item and champion will run to "}
                {"generate an intermediary JSON file with damage formulas for each instance. "}
                {"All the logic related to it is located in crate "}
                <a
                    class={classes!("text-sky-400", "hover:underline", "font-mono")}
                    href={"https://github.com/LuizGomes56/tutorlolv2/tree/master/tutorlolv2_dev"}
                >
                    {"tutorlolv2_dev"}
                </a>
            </p>
        </>
    }
}

#[derive(Clone, Copy, Default, PartialEq)]
enum View {
    #[default]
    Champion,
    Item,
    Rune,
}

#[component]
pub fn Docs() -> Html {
    let view = use_state(View::default);
    let champion_id = use_state(ChampionId::random);
    let item_id = use_state(ItemId::random);
    let rune_id = use_state(RuneId::random);

    let champion_callback = use_setter(&champion_id);
    let item_callback = use_setter(&item_id);
    let rune_callback = use_setter(&rune_id);

    html! {
        <main class={classes!(
            "flex-grow", "flex", "w-full", "overflow-auto",
            "pt-4", "pb-8", "px-6", "flex-col", "gap-4"
        )}>
            <Disclaimer />
            {
                match *view {
                    View::Champion => html! {
                        <CodeDocs<ChampionId>
                            title={"Champion"}
                            value={*champion_id}
                            callback={champion_callback}
                        />
                    },
                    View::Item => html! {
                        <CodeDocs<ItemId>
                            title={"Item"}
                            value={*item_id}
                            callback={item_callback}
                        />
                    },
                    View::Rune => html! {
                        <CodeDocs<RuneId>
                            title={"Rune"}
                            value={*rune_id}
                            callback={rune_callback}
                        />
                    }
                }
            }
        </main>
    }
}
